version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: travelx
    volumes:
      - ./app:/usr/src/app
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=True
    command: flask run --host=0.0.0.0
